###
GET http://localhost:3000/

###
GET http://localhost:3000/books

###
GET http://localhost:3000/book/1

###
POST http://localhost:3000/books
Content-Type: application/json

{
    "title": "The Alchemist",
    "author": "Macdonalds",
    "year": 2019
}

###
PUT http://localhost:3000/book/1
Content-Type: application/json

{
    "title": "The Alchemist Updated"
}

###
DELETE http://localhost:3000/book/10